sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"999999\"},{\"id\":99, \"username\":\"ddd\",\"password\":\"limingyang\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.192.180
    port: 5672
    username: admin
    password: admin
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka


management:
  endpoints:
    web:
      exposure:
        include: refresh
